/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_likhogub_HelloJNI */

#ifndef _Included_ru_likhogub_HelloJNI
#define _Included_ru_likhogub_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_likhogub_HelloJNI
 * Method:    sayHello
 * Signature: ([B)[B
 */
JNIEXPORT jobject JNICALL Java_ru_likhogub_HelloJNI_sayHello
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
